export const ERROR_CODES = {
  ROUTING_ERROR: 1,
  INVALID_TYPES_ERROR: 2,
  DATABASE_ERROR: 3,
  SYNTAX_ERROR: 4,
  INVALID_PARAMS: 5,
  NOT_FOUND: 6,
};

export const ERROR_HTTP_CODES = {
  USER_ERROR: 400,
  INTERNAL_SERVER_ERROR: 500,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
};
